In [1]:
!pip install tensorflow tensorflow-gpu pandas matplotlib sklearn
!pip install scikit-multilearn

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB 1.3 MB/s eta 0:00:00


In [2]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np
import nltk
from nltk.stem.porter import PorterStemmer
nltk.download('punkt')

from sklearn.metrics import classification_report

import pickle

import matplotlib.pyplot as plt
import seaborn as sns

import re
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from wordcloud import WordCloud,STOPWORDS
from nltk.stem.snowball import SnowballStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score
from sklearn.metrics import hamming_loss
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import MultinomialNB
from skmultilearn.problem_transform import ClassifierChain
from skmultilearn.problem_transform import LabelPowerset

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
path = "/content/drive/MyDrive/final_year_project/dataset/test.csv"
df = pd.read_csv(path)

In [5]:
df.head()

comment  toxic  severe_toxic  \
0            sebelum anda kencing di atas kerja saya      1             1   
1  Anda, tuan, adalah wira saya. ada peluang anda...      0             0   
2  tahniah dari saya juga, gunakan alat dengan ba...      0             0   
3  penjajaran mengenai subjek ini dan yang berten...      0             0   
4  d'aww! dia sepadan dengan warna latar belakang...      0             0   

   obscene  threat  insult  identity_hate  
0        1       0       1              0  
1        0       0       0              0  
2        0       0       0              0  
3        0       0       0              0  
4        0       0       0              0

In [6]:
# Text preprocessing
stopwords_list= ["abdul","abdullah","acara","anda","ada","adalah","ahmad","air","akan","akhbar","akhir","aktiviti","alam","amat","amerika","anak","anggota","antara","antarabangsa","apa","apabila","april","as","asas","asing","atas","atau","australia","awal","awam","bagaimanapun","bagi","bahagian","bahan","baharu","bahawa","baik","bandar","bank","banyak","barangan","baru","baru-baru","bawah","beberapa","bekas","beliau","belum","berada","berakhir","berbanding","berdasarkan","berharap","berikutan","berjaya","berjumlah","berkaitan","berkata","berkenaan","berlaku","bermula","bernama","bernilai","bersama","berubah","bhd","bidang","bilion","bn","boleh","bukan","bulan","bursa","cadangan","dagangan","dalam","dan","dana","dapat","dari","daripada","dasar","datang","demikian","dengan","depan","derivatives","dewan","di","diadakan","dibuka","dicatatkan","dijangka","diniagakan","dis","disember","ditutup","dolar","dr","dua","dunia","ekonomi","eksekutif","eksport","empat","enam","faedah","feb","global","hadapan","hanya","harga","hari","hasil","hingga","hubungan","ia","iaitu","ialah","indeks","india","indonesia","industri","ini","islam","isnin","isu","itu","jabatan","jalan","jan","jawatan","jawatankuasa","jepun","jika","jualan","juga","julai","jumaat","jumlah","jun","juta","kadar","kalangan","kali","kami","kata","katanya","kaunter","kawasan","ke","keadaan","kecil","kedua","kedua-dua","kedudukan","kekal","kementerian","kemudahan","kenaikan","kenyataan","kepada","kepentingan","keputusan","kerajaan","kerana","kereta","kerja","kerjasama","kes","keselamatan","keseluruhan","kesihatan","ketika","ketua","keuntungan","kewangan","khamis","kini","kira-kira","kita","klci","klibor","komposit","kontrak","kos","kuala","kuasa","kukuh","kumpulan","lagi","lain","langkah","laporan","lebih","lepas","lima","lot","luar","lumpur","mac","mahkamah","mahu","majlis","makanan","maklumat","malam","malaysia","mana","manakala","masa","masalah","masih","masing-masing","masyarakat","mata","media","mei","melalui","melihat","memandangkan","memastikan","membantu","membawa","memberi","memberikan","membolehkan","membuat","mempunyai","menambah","menarik","menawarkan","mencapai","mencatatkan","mendapat","mendapatkan","menerima","menerusi","mengadakan","mengambil","mengenai","menggalakkan","menggunakan","mengikut","mengumumkan","mengurangkan","meningkat","meningkatkan","menjadi","menjelang","menokok","menteri","menunjukkan","menurut","menyaksikan","menyediakan","mereka","merupakan","mesyuarat","minat","minggu","minyak","modal","mohd","mudah","mungkin","naik","najib","nasional","negara","negara-negara","negeri","niaga","nilai","nov","ogos","okt","oleh","operasi","orang","pada","pagi","paling","pameran","papan","para","paras","parlimen","parti","pasaran","pasukan","pegawai","pejabat","pekerja","pelabur","pelaburan","pelancongan","pelanggan","pelbagai","peluang","pembangunan","pemberita","pembinaan","pemimpin","pendapatan","pendidikan","penduduk","penerbangan","pengarah","pengeluaran","pengerusi","pengguna","pengurusan","peniaga","peningkatan","penting","peratus","perdagangan","perdana","peringkat","perjanjian","perkara","perkhidmatan","perladangan","perlu","permintaan","perniagaan","persekutuan","persidangan","pertama","pertubuhan","pertumbuhan","perusahaan","peserta","petang","pihak","pilihan","pinjaman","polis","politik","presiden","prestasi","produk","program","projek","proses","proton","pukul","pula","pusat","rabu","rakan","rakyat","ramai","rantau","raya","rendah","ringgit","rumah","sabah","sahaja","saham","sama","sarawak","satu","sawit","saya","sdn","sebagai","sebahagian","sebanyak","sebarang","sebelum","sebelumnya","sebuah","secara","sedang","segi","sehingga","sejak","sekarang","sektor","sekuriti","selain","selama","selasa","selatan","selepas","seluruh","semakin","semalam","semasa","sementara","semua","semula","sen","sendiri","seorang","sepanjang","seperti","sept","september","serantau","seri","serta","sesi","setiap","setiausaha","sidang","singapura","sini","sistem","sokongan","sri","sudah","sukan","suku","sumber","supaya","susut","syarikat","syed","tahap","tahun","tan","tanah","tanpa","tawaran","teknologi","telah","tempat","tempatan","tempoh","tenaga","tengah","tentang","terbaik","terbang","terbesar","terbuka","terdapat","terhadap","termasuk","tersebut","terus","tetapi","thailand","tiada","tidak","tiga","timbalan","timur","tindakan","tinggi","tun","tunai","turun","turut","unit","untuk","untung","urus","usaha","utama","walaupun","wang","wilayah","yang"]


def process_text(comment):
   # Remove HTML tags
    comment = re.sub('<.*?>', '', str(comment))
    # Remove non-alphabetic characters and convert to lowercase
    comment = re.sub('[^a-zA-Z]', ' ' , str(comment)).lower()
    # Tokenize the text
    words = nltk.word_tokenize(comment)
    # Remove stopwords
    words = [w for w in words if w not in stopwords_list]
    # Join the words back into a string
    comment = ' '.join(words)
    return comment


df['comment'] = df['comment'].apply(process_text)

In [7]:
df['comment'][:5]

0                                              kencing
1                              tuan wira ingat halaman
2                        tahniah gunakan alat bercakap
3             penjajaran subjek bertentangan dulithgow
4    d aww dia sepadan warna latar belakang seolah ...
Name: comment, dtype: object

In [8]:
X = df["comment"]
y = np.asarray(df[df.columns[1:]])
vectorizer = TfidfVectorizer(max_features=2500, max_df=0.9)
vectorizer.fit(X)

TfidfVectorizer(max_df=0.9, max_features=2500)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

X_train_tfidf = vectorizer.transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)


In [10]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression

model = MultiOutputClassifier(LogisticRegression()).fit(X_train_tfidf, y_train)

In [11]:
prediction = model.predict(X_test_tfidf)
prediction

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [12]:
from sklearn.metrics import accuracy_score
print('Accuracy Score: ', accuracy_score(y_test, prediction))
from sklearn.metrics import hamming_loss
print('Hamming Loss: ', round(hamming_loss(y_test, prediction),2))

Accuracy Score:  0.9053477278433342
Hamming Loss:  0.03


In [14]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = model.predict(X_test_tfidf)
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Precision:', precision_score(y_test, y_pred, average='micro'))
print('Recall:', recall_score(y_test, y_pred, average='micro'))
print('F1 score:', f1_score(y_test, y_pred, average='micro'))

Accuracy: 0.9053477278433342
Precision: 0.8275862068965517
Recall: 0.29171270718232045
F1 score: 0.4313725490196078


In [15]:
# Use our trained model to predict
def detector(text, model=model):
  text = vectorizer.transform([text]).toarray()
  prediction = model.predict(text)
  print(prediction)
  # Assuming that you have a list of labels for each column
  column_labels = df.columns[1:]
  # Convert binary predictions to labels
  predicted_labels = [column_labels[i] for i in range(len(column_labels)) if prediction[0, i] == 1]
  print(f'Predicted Labels: {predicted_labels}\n')


detector("saya sayang kamu")
detector("pergi mati bodoh")
detector("orang ini sampah")
detector("")

[[0 0 0 0 0 0]]
Predicted Labels: []

[[1 0 1 0 1 0]]
Predicted Labels: ['toxic', 'obscene', 'insult']

[[1 0 0 0 0 0]]
Predicted Labels: ['toxic']

[[0 0 0 0 0 0]]
Predicted Labels: []



In [ ]:
import joblib
# saving our model # model - model , filename-model_jlib
joblib.dump(model , 'model_jlib')

In [ ]:
with open('model_pkl', 'wb') as files:
    pickle.dump(model, files)

In [ ]:
with open('vectorizer.pkl', 'wb') as file:
    pickle.dump(vectorizer, file)